"""Markdown views: trail.md (feature in a sprint), sprint.md, features/<feature>.md and index.md.

Derived files: rebuilt deterministically from the journals (byte-identical for the same journals and the
same verify-report.json), never evidence themselves."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from .common import PROJECT_KEY, UNASSIGNED, read_json, short, write_text
from .model import Model, actor_label, describe, gate_text, hhmm, is_flagged

STAGE_GLYPH = {"not": "○", "entered": "●", "reentered": "●↺", "completed": "✔"}


def esc(text: Any) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def _evidence_links(ev: Dict[str, Any]) -> str:
    names = []
    for ref in ev.get("evidence") or []:
        if ref.get("path"):
            names.append(f"[{ref['name']}]({ref['path']})")
        else:
            names.append(esc(ref.get("name")))
    return ", ".join(names) or "—"


def _label(model: Model, ev: Dict[str, Any]) -> str:
    lab = model.label(ev)
    return {"verified": "✔", "ephemeral": "◌", "unanchored": "·", "mismatch": "✖"}.get(lab or "", "")


def table(rows: List[List[str]], header: List[str]) -> List[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(esc(c) if not str(c).startswith("[") else str(c) for c in row) + " |" for row in rows]
    return out


def event_rows(model: Model, events: List[Dict[str, Any]], with_feature: bool = False, links: bool = True) -> List[List[str]]:
    rows = []
    for ev in events:
        title, detail = describe(ev)
        prefix = "⚠ " if is_flagged(ev) and not title.startswith("⚠") else ""
        row = [str(ev.get("seq")), hhmm(ev.get("at")), actor_label(ev.get("actor"), ev.get("data")), prefix + title, detail]
        if with_feature:
            row.insert(1, Path(str(ev.get("feature"))).name if ev.get("feature") else PROJECT_KEY)
        row.append(_evidence_links(ev) if links else str(len(ev.get("evidence") or [])))
        if model.verification:
            row.append(_label(model, ev))
        rows.append(row)
    return rows


def _header(model: Model, with_feature: bool = False) -> List[str]:
    h = ["#", "When", "Actor", "Event", "Detail", "Evidence"]
    if with_feature:
        h.insert(1, "Feature")
    if model.verification:
        h.append("Golden")
    return h


def open_items_lines(model: Model, key: Optional[str]) -> List[str]:
    items = model.open_items(key)
    parts = []
    if items["escalations"]:
        parts.append(f"{len(items['escalations'])} escalation(s) undecided ({'; '.join(i.split(': ', 1)[-1] for i in items['escalations'][:3])})")
    if items["decisions"]:
        parts.append(f"{len(items['decisions'])} decision(s) pending")
    if items["commands"]:
        parts.append(f"{len(items['commands'])} command(s) still open")
    if items["expiring"]:
        parts.append("; ".join(i.split(': ', 1)[-1] for i in items["expiring"][:3]))
    return parts


def chain_line(model: Model, key: str, sprint: Optional[str]) -> str:
    cs = model.chain_summary(key)
    bits = [f"{cs['count']} events in the chain · head {short(cs['head'])}"]
    if sprint:
        seal = model.seal(sprint)
        if seal:
            bits.append(f"sprint sealed {str(seal.get('at'))[:10]} (seal {short(seal.get('hash'))})")
    if model.verification:
        g = (model.verification.get("golden") or {})
        labels = {}
        for ev in model.chains.get(key, []):
            lab = model.label(ev)
            if lab:
                labels[lab] = labels.get(lab, 0) + 1
        internal = (model.verification.get("internal") or {}).get("status")
        bits.append(f"last verify: internal {internal}" + (", golden " + ", ".join(f"{v} {k}" for k, v in sorted(labels.items())) if labels else "")
                    + (f" ({g.get('status')})" if g.get("status") else ""))
    return " · ".join(bits)


def render_trail(model: Model, key: str, sprint: str) -> str:
    events = [e for e in model.chains.get(key, []) if e.get("_sprint_dir") == sprint]
    entry = model.sprint_entry(sprint)
    lines = [f"# {key} — Sprint {sprint}" + (f" ({entry['name']})" if entry.get("name") and sprint != UNASSIGNED else ""), ""]
    if key != PROJECT_KEY:
        lines.append(f"**Stages:** {model.stage_line(key, sprint)}  ")
    oi = open_items_lines(model, key)
    lines.append(f"**Open items:** {' · '.join(oi) if oi else 'none'}  ")
    lines.append(f"**Chain:** {chain_line(model, key, sprint)}")
    lines.append("")
    lines.append("> Generated by auditGuard from `journal.jsonl` - the journal is the record; this page is a view.")
    lines.append("")
    stage_names = model.cfg.stage_names()
    if key != PROJECT_KEY:
        st = model.status(key)
        buckets: Dict[Optional[str], List[Dict[str, Any]]] = {}
        for ev in events:
            buckets.setdefault(ev.get("stage") if ev.get("stage") in stage_names else None, []).append(ev)
        for name in stage_names + [None]:
            evs = buckets.get(name)
            if not evs:
                continue
            if name is None:
                lines.append("## Before the first stage")
            else:
                head = f"## {name.capitalize()}"
                if st.entered.get(name):
                    head += f" — entered {hhmm(st.entered[name])}"
                if st.completed.get(name):
                    done = st.completed[name] or {}
                    head += f" · completed {hhmm(done.get('at'))} ({done.get('by_kind')})"
                if st.reentered.get(name):
                    head += f" · re-entered {len(st.reentered[name])}×"
                lines.append(head)
            lines.append("")
            lines += table(event_rows(model, evs), _header(model))
            lines.append("")
    else:
        lines.append("## Events")
        lines.append("")
        lines += table(event_rows(model, events), _header(model))
        lines.append("")
    lines += _sections(model, key, sprint)
    return "\n".join(lines).rstrip() + "\n"


def _sections(model: Model, key: Optional[str], sprint: Optional[str], with_feature: bool = False) -> List[str]:
    lines: List[str] = []
    dec = model.decisions(key, sprint)
    lines.append("## Decisions (human in the loop)")
    lines.append("")
    if dec:
        rows = []
        for e in dec:
            d = e.get("data") or {}
            subject = d.get("subject") or e.get("kind")
            verdict = d.get("verdict") or ("★" if e.get("kind") != "decision" else "")
            row = [hhmm(e.get("at")), d.get("by") or (e.get("actor") or {}).get("id"), d.get("role") or (e.get("actor") or {}).get("role") or "",
                   subject, verdict, d.get("reason") or "", f"#{e.get('seq')}"]
            if with_feature:
                row.insert(1, Path(str(e.get("feature"))).name if e.get("feature") else PROJECT_KEY)
            rows.append(row)
        h = ["When", "Who", "Role", "Subject", "Verdict", "Reason", "Event"]
        if with_feature:
            h.insert(1, "Feature")
        lines += table(rows, h)
    else:
        lines.append("None recorded.")
    lines.append("")
    lines.append("## Waivers and deferrals")
    lines.append("")
    wev = model.waiver_events(key, sprint)
    if wev:
        rows = []
        for e in wev:
            d = e.get("data") or {}
            row = [hhmm(e.get("at")), d.get("id"), e["kind"].split(".", 1)[1], d.get("source"),
                   d.get("item") or ", ".join(d.get("rules") or []) or d.get("rule") or "", d.get("status") or "",
                   d.get("reason") or "", d.get("owner") or "", d.get("approver") or "", d.get("expires") or ""]
            if with_feature:
                row.insert(1, Path(str(e.get("feature"))).name if e.get("feature") else PROJECT_KEY)
            rows.append(row)
        h = ["When", "Id", "Change", "Source", "Item / rule", "Status", "Reason", "Owner", "Approver", "Expires"]
        if with_feature:
            h.insert(1, "Feature")
        lines += table(rows, h)
    else:
        lines.append("No waiver changed.")
    lines.append("")
    lines.append("## Gate verdicts")
    lines.append("")
    gv = model.gate_verdicts(key, sprint)
    if gv:
        rows = []
        for e in gv:
            d = e.get("data") or {}
            row = [hhmm(e.get("at")), d.get("tool"), d.get("gate") or d.get("step"), str(d.get("status") or "").upper(),
                   gate_text(d), str(d.get("iterations") or ""), _evidence_links(e)]
            if with_feature:
                row.insert(1, Path(str(e.get("feature"))).name if e.get("feature") else PROJECT_KEY)
            rows.append(row)
        h = ["When", "Tool", "Gate", "Status", "Summary", "Iterations", "Report"]
        if with_feature:
            h.insert(1, "Feature")
        lines += table(rows, h)
    else:
        lines.append("No gate report collected.")
    lines.append("")
    lines.append("## Changes outside recorded commands")
    lines.append("")
    oob = model.oob(key, sprint)
    if oob:
        rows = []
        for e in oob:
            d = e.get("data") or {}
            files = ", ".join(str(c.get("path")) for c in (e.get("changed") or [])[:6])
            flags = ", ".join(f for f, on in (("after sign-off", d.get("after_signoff")), ("after handover", d.get("after_handover"))) if on)
            row = [hhmm(e.get("at")), files, flags, str(d.get("inferred_command") or "").replace("speckit.", ""),
                   ", ".join(sorted(set((d.get("authors") or {}).values()))), f"#{e.get('seq')}"]
            if with_feature:
                row.insert(1, Path(str(e.get("feature"))).name if e.get("feature") else PROJECT_KEY)
            rows.append(row)
        h = ["When", "Files", "Flags", "Inferred command", "Author (committed)", "Event"]
        if with_feature:
            h.insert(1, "Feature")
        lines += table(rows, h)
    else:
        lines.append("None.")
    lines.append("")
    return lines


def render_sprint(model: Model, sprint: str) -> str:
    entry = model.sprint_entry(sprint)
    lines = [f"# Sprint {sprint}" + (f" — {entry['name']}" if entry.get("name") and sprint != UNASSIGNED else ""), ""]
    meta = []
    if entry.get("start") or entry.get("end"):
        meta.append(f"{entry.get('start') or '?'} … {entry.get('end') or '?'}")
    meta.append(f"status **{entry.get('status')}**")
    if entry.get("goal"):
        meta.append(f"goal: {entry['goal']}")
    lines.append(" · ".join(meta) + "  ")
    seal = model.seal(sprint)
    if seal:
        lines.append(f"**Seal:** {seal.get('hash')} — closed by {seal.get('closed_by')} on {str(seal.get('at'))[:16]}"
                     + (f" · {len(seal.get('warnings') or [])} warning(s) at close" if seal.get("warnings") else ""))
        if model.verification:
            g6 = [f for f in (model.verification.get("golden") or {}).get("findings") or [] if f.get("check") == "G6" and f.get("sprint") == sprint]
            lines.append(f"**Anchor:** tag `audit/{sprint}` " + ("✖ " + g6[0].get("reason", "") if g6 else "✔"))
    lines.append("")
    lines.append("## Features and stages")
    lines.append("")
    rows = []
    for key in model.feature_keys():
        evs = [e for e in model.chains[key] if e.get("_sprint_dir") == sprint]
        if not evs:
            continue
        st = model.status(key, sprint)
        cells = []
        for name in st.names:
            state = st.state[name]
            text = STAGE_GLYPH.get(state, "○")
            if state == "completed":
                text += f" {str((st.completed[name] or {}).get('at') or '')[:10]}"
            cells.append(text)
        flagged = sum(1 for e in evs if is_flagged(e))
        rows.append([f"[{key}]({key}/trail.md)"] + cells + [str(len(evs)), f"⚠ {flagged}" if flagged else ""])
    if rows:
        lines += table(rows, ["Feature"] + [n.capitalize() for n in model.cfg.stage_names()] + ["Events", "Flags"])
    else:
        lines.append("No feature activity in this sprint.")
    lines.append("")
    oi = open_items_lines(model, None)
    lines.append(f"**Open items (whole project):** {' · '.join(oi) if oi else 'none'}")
    lines.append("")
    lines += _sections(model, None, sprint, with_feature=True)
    sessions = [e for e in model.events(sprint, PROJECT_KEY) if e.get("kind", "").startswith("session.")]
    lines.append("## Sessions")
    lines.append("")
    if sessions:
        lines += table([[hhmm(e.get("at")), e["kind"].split(".")[1], (e.get("data") or {}).get("agent") or "",
                         short((e.get("data") or {}).get("session"), 12)] for e in sessions], ["When", "Event", "Agent", "Session"])
    else:
        lines.append("None recorded.")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_feature(model: Model, key: str) -> str:
    lines = [f"# {key} — all sprints", "", f"**Stages:** {model.stage_line(key)}  "]
    oi = open_items_lines(model, key)
    lines.append(f"**Open items:** {' · '.join(oi) if oi else 'none'}")
    lines.append("")
    rows = []
    for sprint in model.sprints():
        evs = [e for e in model.chains.get(key, []) if e.get("_sprint_dir") == sprint]
        if not evs:
            continue
        rows.append([f"[{sprint}](../sprints/{sprint}/{key}/trail.md)", model.stage_line(key, sprint), str(len(evs)),
                     f"#{evs[0].get('seq')}–#{evs[-1].get('seq')}"])
    lines += table(rows, ["Sprint", "Stages at the end of the sprint", "Events", "Seq"])
    lines.append("")
    in_force = model.waivers_in_force(key)
    lines.append("## Waivers in force")
    lines.append("")
    if in_force:
        lines += table([[r.get("id"), r.get("source"), r.get("item") or ", ".join(r.get("rules") or []), r.get("status"),
                         r.get("reason") or "", r.get("approver") or "", r.get("expires") or ""] for _, r in in_force],
                       ["Id", "Source", "Item / rule", "Status", "Reason", "Approver", "Expires"])
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index(model: Model) -> str:
    sprints = model.sprints()
    lines = ["# Audit trail", ""]
    v = model.verification
    if v:
        g = v.get("golden") or {}
        lines.append(f"**Last verification:** internal {(v.get('internal') or {}).get('status')} · golden {g.get('status', 'not run')}"
                     + f" · {len([f for f in g.get('findings') or [] if f.get('label') in ('mismatch', 'unexplained_commit')])} finding(s)")
    oi = open_items_lines(model, None)
    lines.append(f"**Open items:** {' · '.join(oi) if oi else 'none'}  ")
    lines.append(f"**Waivers in force:** {len(model.waivers_in_force())}")
    lines.append("")
    header = ["Feature"]
    for s in sprints:
        e = model.sprint_entry(s)
        header.append(f"[{s}](sprints/{s}/sprint.md)" + (" 🔒" if model.seal(s) else (" (open)" if e.get("status") == "open" else "")))
    rows = []
    for key in model.keys():
        row = [f"[{key}](features/{key}.md)" if key != PROJECT_KEY else key]
        for s in sprints:
            cell = model.cell(key, s)
            if not cell.get("events"):
                row.append("–")
                continue
            if key == PROJECT_KEY:
                row.append(f"{cell['events']} event(s)")
                continue
            text = " · ".join(f"{c['stage']} {STAGE_GLYPH.get(c['state'], '○')}" for c in cell.get("stages") or []) or f"{cell['events']} event(s)"
            if cell.get("flagged"):
                text += f" ⚠{cell['flagged']}"
            row.append(f"[{text}](sprints/{s}/{key}/trail.md)")
        rows.append(row)
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    lines += out
    lines.append("")
    lines.append("Legend: ○ not started · ● in progress · ●↺ re-entered · ✔ completed · ⚠ flagged (out-of-band change, "
                 "re-entry, escalation) · 🔒 sealed")
    lines.append("")
    return "\n".join(lines)


def load_verification(cfg: Any) -> Optional[Dict[str, Any]]:
    return read_json(cfg.audit_root / "verify-report.json", None)


def render_all(store: Any, cfg: Any, *, keys: Optional[List[str]] = None, sprints: Optional[List[str]] = None) -> List[Path]:
    model = Model(store, cfg, load_verification(cfg))
    written: List[Path] = []
    all_sprints = model.sprints()
    for sprint in all_sprints:
        if sprints is not None and sprint not in sprints:
            continue
        folder = store.sprints_dir / sprint
        if not folder.is_dir():
            continue
        _write_if_changed(folder / "sprint.md", render_sprint(model, sprint), written)
        for key in model.keys():
            if keys is not None and key not in keys:
                continue
            if not (folder / key / "journal.jsonl").is_file():
                continue
            _write_if_changed(folder / key / "trail.md", render_trail(model, key, sprint), written)
    for key in model.feature_keys():
        if keys is not None and key not in keys:
            continue
        _write_if_changed(store.audit / "features" / f"{key}.md", render_feature(model, key), written)
    _write_if_changed(store.audit / "index.md", render_index(model), written)
    return written


def _write_if_changed(path: Path, text: str, written: List[Path]) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return
    write_text(path, text)
    written.append(path)
